version: "2"
checks:
  similar-code:
    enabled: true
    config:
      languages:
      - javascript
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_patterns:
- node_modules/
- src/test/
